config: "/home/tipriest/Documents/CVTask/mmsegmentation/configs/mask2former/mask2former_r50_8xb2-160k_waterworld-512x512.py"
checkpoint: "/home/tipriest/Documents/CVTask/mmsegmentation/work_dirs/mask2former_r50_8xb2-160k_waterworld-512x512/iter_150000.pth"
device: "cuda:0"
alpha: 0.5
input_rgb: "/camera_face/color/image_raw"
input_depth: "/camera_face/depth/image_raw"
output_cloud: "/seg_pointcloud/points"
output_overlay: "/seg_pointcloud/overlay"
# palette: [[r, g, b], ...] for each class id, leave empty to use model palette
palette:
  - [0, 255, 0]       # class 0
  - [255, 0, 0]     # class 1
  - [0, 0, 255]     # class 2
  - [20, 20, 20]     # class 3
sample_rate: 100
depth_scale: 1.0
frame_id: "camera_optical_face"
resize_width: 0
resize_height: 0
# intrinsics fx, fy, cx, cy
intrinsics: [554.5091528011569, 554.5091528011569, 960.0, 540.0]
extrinsics: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]
